[versions]
agp = "8.7.2"
r8_annotations = "v0.0.2"
androidvmtools = "7a0f308054"
zygisk = "98122c30f7"

[libraries]
androidvmtools = { module = "com.github.vova7878:AndroidVMTools", version.ref = "androidvmtools" }
r8-annotations = { module = "com.github.vova7878:R8Annotations", version.ref = "r8_annotations" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
java-zygisk = { id = "com.github.vova7878.ZygoteLoader", version.ref = "zygisk" }

